title: Incorrect tags or properties
hero_image: images/banner.png
description: Incorrect tags or properties
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Incorrect tags or properties
